- name: "create config backup"
  hosts: all
  connection: network_cli
  gather_facts: no
  serial: 1

  vars:
    ansible_network_os: vyos

  tasks:

     - import_tasks: directory.yml
     - import_tasks: auth.yml
     - import_tasks: backup.yml
     - import_tasks: sanitize_backup.yml